version: '3.9'

services:
  todo-app:
    image: ghcr.io/anegm10/todo-list-app:latest
    container_name: todo-app
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      # if you use Mongo, pass it from .env file
      - mongoDbUrl=${mongoDbUrl}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 todo-app

