apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: ghcr.io/anegm10/todo-list-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: mongoDbUrl
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: uri
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
      imagePullSecrets:
        - name: ghcr-secret

